### PR TITLE
fixHotelManagerDiagram

### PR DESCRIPTION
**Pull request by vzhang23**
fix the diagram

### CODE REVIEW

**Comment by vzhang23** [comment]
Screenshot 2022-10-13 153853

**Comment by mclhtay** [comment]
Why is this change needed? Why did you:
1. remove the extension of CheckAvialableRoom <--extend-- ReserveARoom
2. add modifyReservation? If a customer wishes to modify, they can simply cancel and then re-reserve
3. remove checkReserveRoom <--extend-- checkInCustomer ?

**Comment by vzhang23** [comment]
> Why is this change needed? Why did you:
> 
> 1. remove the extension of CheckAvialableRoom <--extend-- ReserveARoom
> 2. add modifyReservation? If a customer wishes to modify, they can simply cancel and then re-reserve
> 3. remove checkReserveRoom <--extend-- checkInCustomer ?

this is the original diagram at the begining, for some reason when I add a hotel booker diagram this diagram changes to the botel booker diagram, and I am just reverse the diagram back.

**Comment by mclhtay** [comment]
It says you are modifying hotel manager. Please do not modify it. The current version of HotelManager.drawio under the `main` branch is the most original one.

**Comment by mclhtay** [comment]
I am going to mark this PR as closed because the HotelManager use-case diagram in `main` does not need to be modified. Your changes to it was reversed back yesterday. Please check commit history.

**Pull request closed without merging**
