### PR TITLE
Update login usecase

### PR DESCRIPTION
**Pull request by tbuwadi**
Hi, I updated the login use case by removing the actor on the right and updating the use case diagram title to "Hotel System". Please review

### CODE REVIEW

**Review by mclhtay — CHANGES_REQUESTED** [review]
Can you include a screenshot of your new diagram?

**Comment by tbuwadi** [comment]
image

**Comment by tbuwadi** [comment]
@mclhtay

**Comment by tbuwadi** [comment]
image

**Comment by tbuwadi** [comment]
new screenshot uploaded @mclhtay

**Comment by mclhtay** [comment]
A few things:
1. use case diagram is how the customer views the system, so the use case "Update Customer Table" should not be in the diagram, it is something the system does hidden from the user.
2. I don't think the numerous "Provides" are actually use cases, they are all a part of "Register" and not separate use cases, @vzhang23's your opinion on this?
3. ^ same with "Username & Password Details"

**Comment by vzhang23** [comment]
I think it might be better for you to follow the format of me and Carter's use case(is it is possible), so later if we want to combine them, it will be easier to do so.

**Comment by tbuwadi** [comment]
I see what you are saying, makes sense. This is the updated use case @mclhtay @vzhang23 
image

**Comment by mclhtay** [comment]
Why does Register include Authentication?

**Comment by tbuwadi** [comment]
authenticate that the username is unique, password is valid, etc @mclhtay

**Review by mclhtay — APPROVED** [review]

**Pull request merged**
