### PR TITLE
Modify Architecture diagram

### PR DESCRIPTION
**Pull request by vzhang23**
Add reservation related architecture
image

### CODE REVIEW

**Comment by mclhtay** [comment]
why do we need a reservation controller? Methods involved in reserving a room should be under the room controller.

**Comment by vzhang23** [comment]
If we want to track history of reservation or change the status of reservation(like change the bill), it does not make much sense to put it under room controller because we are not making any changes to anything related to attribute in room object

**Comment by mclhtay** [comment]
> If we want to track history of reservation or change the status of reservation(like change the bill), it does not make much sense to put it under room controller because we are not making any changes to anything related to attribute in room object

If you want to do it this way then you have to remember to update the reserve_room and cancel_reservation methods in RoomController when you get to it.

**Review by mclhtay — DISMISSED** [review]
Approve on the basis of comment.

**Review by mclhtay — COMMENTED** [review]
One more comment though, in this case, the customer should also have stay history under the same logic as reservation history, i.e., as a customer, i can see the history of how long I stayed in a room. Are you going to combine that logic under the reservation model/controller?

**Comment by vzhang23** [comment]
image

**Comment by mclhtay** [comment]
Where is HistoryModel, CustomerController and HistoryController?

**Pull request closed without merging**
